### ISSUE TITLE
Crashes clients on 1.19.2 when joining server

### ISSUE THREAD

**Issue by Nycto97** [Lgmrszd/CompressedCreativity#33] opened 2023-09-21 05:40 UTC
I'll leave the log here. Also, I use /flywheel backend off, I don't know if this causes any issues with your mod.

https://bytebin.lucko.me/HAfMfj2BMX

It says Suspected Mods: Forge (forge), Minecraft (minecraft), Compressed Creativity (compressedcreativity), Create (create), Dungeons Libraries (dungeons_libraries)

**Comment by Lgmrszd** [comment] 2023-10-07 21:39
The log seems to be gone, can you reupload it?

**Comment by Lgmrszd** [comment] 2023-10-08 12:46
Alright, I was able to reproduce this bug. The reason it happens is because when I attach pneumatic capability to the backtank, it checks it's enchantment level (to get capacity), but Dungeon Libraries changes it in a way that checking item for enchantments also checks for capabilities (`getTagEnchantmentLevel` in `EnchantmentHelper`.

I think I managed to fix it in the upcoming 0.1.8 update, and if it still breaks you should be able to disable pneumatic capability of a backtank with `backtank_compat_item` in Compressed Creativity config (due an oversight in my mod that won't work on current version)

**Comment by Lgmrszd** [comment] 2023-10-08 14:24
Fixed in https://github.com/Lgmrszd/CompressedCreativity/commit/aaeeb7eb8d32d67cca643a6e42da36bb680720bd

**Closed as completed by Lgmrszd** 2023-10-08 14:24 UTC
