### ISSUE TITLE
Game mod loading crash

### ISSUE THREAD

**Issue by 123qwqeq** [Lgmrszd/CompressedCreativity#39] opened 2023-11-02 00:42 UTC
[crash-2023-11-02_08.35.18-fml.txt](https://github.com/Lgmrszd/CompressedCreativity/files/13232914/crash-2023-11-02_08.35.18-fml.txt)

**Comment by Reicere** [comment] 2023-11-07 21:20
I had the same issue, tracked it down to modernfix by comparing modlists.
Apparently the pack I was building off of had enabled its known-breaking mixin.perf.dynamic_resources feature
Disabling that option fixed it for me.

**Comment by Lgmrszd** [comment] 2023-11-08 16:05
I am unable to replicate this crash with same version of ModernFix (5.9.0) and same version of Forge (47.2.1) as in provided log.
@Reicere what mods you also had installed when crash happened?

**Comment by Lgmrszd** [comment] 2023-11-08 16:08
@123qwqeq do you still get this crash?
Can you test the following, just in case?
1) Updating ModernFix and other mods (if this is something that other mods caused on previous versions and resolved now)
2.1) Downgrading Forge loader to 47.1.0 or whatever minimal version is required your installed mods (there's been reports of Forge 47.2.* being unstable), or....
2.2) Switching to NeoForge loader (same reason as above)

**Comment by Reicere** [comment] 2023-11-08 16:20
Unfortunately my pack is a 200 mod dumpster fire, running on 47.1.3 forge w/ the fabric connector w/ imported configs from another pack. So not really worth much, Ill try with ops list and report back.

**Comment by Reicere** [comment] 2023-11-08 17:46
Reproduced with both an exact copy of ops pack and a minimal subset. Its definitely the config

Minimal repro, all default configs except dynamic_resources enabled in modernfix
[crash-2023-11-08_12.41.19-fml.txt](https://github.com/Lgmrszd/CompressedCreativity/files/13299705/crash-2023-11-08_12.41.19-fml.txt)

**Comment by Lgmrszd** [comment] 2023-11-10 20:18
Oh yeah I wasn't able to reproduce this because I didn't enable that option.
With it enabled I get the crash.
I don't know if fixing this is in the current scope because it is said it can break things and is disabled by default.
Though I do register my partial models the same way Create does, and it doesn't crash when loading with just Create :thinking:

**Comment by Lgmrszd** [comment] 2023-11-10 21:28
Ok so I changed things in 1.20.1 that I thought Create also did but it seems it didn't, and turns out my mod should've crashed by itself but it didn't?? Modding can be so weird sometimes.

**Comment by Lgmrszd** [comment] 2023-11-10 21:50
ok yeah I've Changed Things I Shouldn't Have :tm: so I'll revert that and check if it works
(if it does I'll include that in next small update)

**Comment by Lgmrszd** [comment] 2023-11-10 22:21
Okay it works when I revert it
What's more surprising is that it didn't crash by itself in the first place...

**Comment by Lgmrszd** [comment] 2023-11-15 23:51
fixed in 0.1.8.b

**Closed as completed by Lgmrszd** 2023-11-15 23:51 UTC
